import { Project, Certification, EducationInfo, SkillCategory } from './types';

export const personalInfo = {
  name: 'Ansuman Sahu',
  title: 'Computer Science & Engineering Student',
  subtitle: 'Software Development • Artificial Intelligence • Cybersecurity',
  location: 'Bhubaneswar, Odisha, India',
  email: 'ansuman.slplindia@gmail.com',
  linkedin: 'https://www.linkedin.com/in/ansuman-sahu-ba0313374/',
  github: 'https://github.com/AnsumanSahu9966',
  instagram: 'https://www.instagram.com/ansuman._.sahu/',
  gender: 'Male',
  pronouns: 'He/Him',
  summary: 'I am a passionate sophomore pursuing a B.Tech. in Computer Science and Engineering at Siksha \'O\' Anusandhan (SOA) ITER. I actively build projects leveraging Java and data structures, and I have a deep curiosity for Artificial Intelligence, Machine Learning, and Cybersecurity. Driven by continuous learning, I enjoy solving complex problems, writing clean code, and crafting intuitive software solutions that make a real impact. Beyond my core academic coursework, I consistently seek out challenging certifications and practical hands-on experiences to sharpen my technical acumen. I believe in a collaborative approach to engineering, bridging the gap between elegant algorithms and engaging user experiences. Whether I am architecting a new application backend, exploring advanced AI concepts, or diving deep into security protocols, I am committed to continuous growth and building technology that solves real-world challenges effectively.',
};

export const educationHistory: EducationInfo[] = [
  {
    degree: 'B.Tech. in Computer Science and Engineering',
    institution: 'Institute of Technical Education and Research (ITER), Siksha \'O\' Anusandhan (SOA) University',
    location: 'Bhubaneswar, Odisha',
    duration: 'Aug 2025 – Present (Expected 2029)',
    grade: 'CGPA: 7.66 / 10',
    highlights: [
      'Focusing on Software Development, Artificial Intelligence, and Data Structures & Algorithms',
      'Relevant Coursework: Programming in Java, Object-Oriented Programming, Data Structures, Computer Organization, Database Fundamentals, Operating Systems, Machine Learning Fundamentals, Engineering Mathematics',
    ],
  },
  {
    degree: 'Higher Secondary Education (Class XI - XII)',
    institution: 'M.S. Junior College',
    location: 'Hyderabad, Telangana',
    duration: 'Completed 2025',
    grade: 'Percentage: 63.8%',
    highlights: ['Specialization in Mathematics, Physics, and Chemistry'],
  },
  {
    degree: 'Primary to Secondary Education (till Class X)',
    institution: 'St. Adam\'s High School',
    location: 'Hyderabad, Telangana',
    duration: 'Completed 2023',
    grade: 'CGPA: 8.2 / 10',
  },
];

export const projectsList: Project[] = [
  {
    id: 'student-record',
    title: 'Student Record Management System',
    technologies: ['Java', 'OOP', 'Data Structures'],
    description: 'Developed a comprehensive menu-driven Student Record Management System using a custom-built Singly Linked List from scratch. Implemented core CRUD operations, searching, sorting, record updates, duplicate validation, list reversal, top-performer identification, and class performance statistics without relying on any standard Java Collections Framework libraries.',
    skills: ['Java', 'OOP', 'Linked Lists', 'CRUD Operations', 'Data Structures', 'Algorithmic Logic'],
    category: 'academic',
    githubUrl: 'https://github.com/AnsumanSahu9966/Java-Projects/blob/main/StudentRecordSystem.java',
  },
  {
    id: 'dsa-toolkit',
    title: 'Data Structures & Algorithms Toolkit',
    technologies: ['Java', 'Arrays', 'Linked Lists'],
    description: 'Designed and implemented an interactive, console-based Data Structures Toolkit containing custom implementations of fundamental ADTs including Stack, Queue, Singly Linked List, and Doubly Linked List. Designed with both array-based (sequential) and dynamic memory (linked) implementations, offering seamless insertion, deletion, traversal, linear/binary searching, sorting, and reversal capabilities.',
    skills: ['Java', 'Stack & Queue', 'Linked Lists', 'Array Manipulation', 'DSA Foundations', 'Memory Management Concepts'],
    category: 'dsa',
    githubUrl: 'https://github.com/AnsumanSahu9966/Java-Projects/blob/main/DSA%20Toolkit.java',
  },
  {
    id: 'java-oop-showcase',
    title: 'Java OOP Architectural Showcase',
    technologies: ['Java', 'OOP Principles'],
    description: 'Built an elaborate collection of object-oriented Java applications specifically designed to demonstrate and showcase core OOP pillars: multi-level inheritance, abstraction, interfaces, polymorphism, constructor overloading, and strict encapsulation. Modeled practical, intuitive systems such as Vehicle hierarchies, Shape calculators (Circle, Rectangle), Complex Number math structures, and customizable Duck behaviors.',
    skills: ['Java', 'OOP Pillars', 'Inheritance & Abstraction', 'Polymorphism', 'Interfaces', 'Encapsulation'],
    category: 'showcase',
    githubUrl: 'https://github.com/AnsumanSahu9966/Java-Projects/blob/main/OopShowcase.java',
  },
  {
    id: 'generic-library',
    title: 'Java Generic Utility Library',
    technologies: ['Java', 'Generics', 'Exception Handling'],
    description: 'Developed a robust, highly reusable generic helper library and utility class suite supporting type-safe operations. Integrated recursive search and sort algorithms, custom exception-handling frameworks, type-agnostic array manipulations, counting filters, and search predicates to showcase Java generics proficiency.',
    skills: ['Java', 'Generics', 'Recursion', 'Custom Exception Handling', 'Type Safety', 'Utility Development'],
    category: 'utility',
    githubUrl: 'https://github.com/AnsumanSahu9966/Java-Projects/blob/main/GenericsLibrary.java',
  },
  {
    id: 'java-utility-suite',
    title: 'Modular Java Utility Suite',
    technologies: ['Java', 'Modular Programming'],
    description: 'Developed a collection of high-utility console applications including a fully fledged scientific calculator, a password strength validator (enforcing length, digits, casing, and special chars), a palindrome string checker, advanced mathematical solvers, and multi-field validation modules using modular code layout and method overloading.',
    skills: ['Java', 'Methods Overloading', 'String Parsing', 'Validation Modules', 'Modular Architecture'],
    category: 'utility',
    githubUrl: 'https://github.com/AnsumanSahu9966/Java-Projects/blob/main/JavaUtilitySuite.java',
  },
  {
    id: 'apexplanet-cyber-lab',
    title: 'Virtual Cybersecurity Lab Setup',
    technologies: ['Kali Linux', 'VirtualBox', 'Metasploitable2'],
    description: 'Built a complete virtual cybersecurity lab environment as part of the ApexPlanet Cybersecurity Internship. Configured isolated host-only networks, practiced essential Linux terminal commands, performed network reconnaissance using Nmap, and captured/analyzed network traffic using Wireshark to understand penetration testing workflows.',
    skills: ['CyberSecurity', 'Ethical Hacking', 'Nmap', 'Wireshark', 'Burp Suite', 'Linux', 'Networking', 'Penetration Testing'],
    category: 'cybersecurity',
    githubUrl: 'https://github.com/AnsumanSahu9966/ApexPlanet-Cybersecurity-Internship',
  },
  {
    id: 'graph-composer',
    title: 'Markov Chain Song & Text Composer',
    technologies: ['Python', 'Markov Chains', 'Graph Theory', 'NLP'],
    description: 'Built a graph-based text generation model using Markov Chains to represent probabilistic relationships between words in song lyrics and text corpora. Generates unique lyric compositions and interpretive poetry by performing weighted stochastic traversals over graph nodes.',
    skills: ['Python', 'Markov Chains', 'Graph Algorithms', 'Natural Language Processing', 'Probabilistic Modeling'],
    category: 'python',
    githubUrl: 'https://github.com/AnsumanSahu9966/Python-Learnt-topics/tree/master/graph-composer-master',
  },
  {
    id: 'pyphotoshop',
    title: 'PyPhotoshop Image Processing Engine',
    technologies: ['Python', 'Image Processing', 'Matrix Math', 'PNG I/O'],
    description: 'Engineered an image processing library implementing core visual filters from scratch without high-level CV dependencies. Features contrast and brightness adjustment, box blur algorithms, Sobel edge detection, and a pure Python PNG reader/writer.',
    skills: ['Python', 'Computer Vision Basics', 'Matrix Transformations', 'File Format I/O', 'Algorithm Optimization'],
    category: 'python',
    githubUrl: 'https://github.com/AnsumanSahu9966/Python-Learnt-topics/tree/master/pyphotoshop-main',
  },
  {
    id: 'sudoku-solver',
    title: 'Backtracking Sudoku Solver Engine',
    technologies: ['Python', 'Backtracking', 'Recursion', '2D Arrays'],
    description: 'Developed an automated 9x9 Sudoku puzzle solver utilizing recursive constraint satisfaction and depth-first backtracking algorithms. Safely evaluates matrix grid rules to solve complex numerical puzzles in sub-second runtimes.',
    skills: ['Python', 'Recursive Backtracking', 'Constraint Satisfaction', 'Matrix Operations', 'Algorithmic Optimization'],
    category: 'python',
    githubUrl: 'https://github.com/AnsumanSahu9966/Python-Learnt-topics/tree/master/sudoku-main',
  },
  {
    id: 'minesweeper',
    title: 'Recursive 2D Terminal Minesweeper',
    technologies: ['Python', 'Recursion', '2D Arrays', 'Terminal UI'],
    description: 'Implemented a 2D Minesweeper game engine for the command line with custom grid initialization and random bomb placement. Features recursive zero-neighbor expansion (flood fill algorithm) when digging non-bomb cells.',
    skills: ['Python', 'Flood Fill Algorithm', 'Recursion', '2D Grid Structures', 'Game State Logic'],
    category: 'python',
    githubUrl: 'https://github.com/AnsumanSahu9966/Python-Learnt-topics/tree/master/minesweeper-main',
  },
  {
    id: 'tic-tac-toe-ai',
    title: 'Tic-Tac-Toe Minimax AI Engine',
    technologies: ['Python', 'Minimax Algorithm', 'Game Theory', 'AI'],
    description: 'Built an interactive Tic-Tac-Toe engine in Python featuring an unbeatable Minimax decision-tree AI opponent. Evaluates state trees to choose optimal moves, alongside support for human-vs-human local matches.',
    skills: ['Python', 'Minimax AI', 'Game Theory', 'Decision Trees', 'Algorithmic Strategy'],
    category: 'python',
    githubUrl: 'https://github.com/AnsumanSahu9966/Python-Learnt-topics/tree/master/tic-tac-toe-master',
  },
  {
    id: 'hangman-game',
    title: 'Command-Line Hangman Engine',
    technologies: ['Python', 'Set Operations', 'String Parsing', 'CLI'],
    description: 'Created a modular CLI Hangman game utilizing Python set operations for constant-time letter validation, dictionary word corpus importing, and dynamic visual state rendering for remaining attempts.',
    skills: ['Python', 'Set Operations', 'String Manipulation', 'CLI UX', 'Error Handling'],
    category: 'python',
    githubUrl: 'https://github.com/AnsumanSahu9966/Python-Learnt-topics/tree/master/hangman-master',
  },
  {
    id: 'guess-number',
    title: 'Dual-Mode Guess the Number Engine',
    technologies: ['Python', 'Binary Search', 'Randomization', 'CLI'],
    description: 'Designed a dual-mode number guessing game in Python. Features player guessing with feedback hints and an automated computer mode where the AI leverages binary search to guess player-selected numbers in logarithmic time.',
    skills: ['Python', 'Binary Search Algorithm', 'Logarithmic Complexity', 'User Input Processing'],
    category: 'python',
    githubUrl: 'https://github.com/AnsumanSahu9966/Python-Learnt-topics/tree/master/guess-the-number-master',
  },
  {
    id: 'beginner-python-suite',
    title: 'MadLibs & Beginner Python Project Suite',
    technologies: ['Python', 'String Operations', 'Control Flow', 'CLI'],
    description: 'A curated collection of foundational Python applications including a MadLibs story generator, a simulated mainframe login hacking experience, a random selector utility, and interactive Rock-Paper-Scissors.',
    skills: ['Python', 'String Manipulation', 'CLI Control Flow', 'Input Handling', 'Functional Design'],
    category: 'python',
    githubUrl: 'https://github.com/AnsumanSahu9966/Python-Learnt-topics/tree/master/beginner-projects-master',
  },
];

export const certificationsList: Certification[] = [
  {
    id: 'nasha-mukt',
    title: 'Nasha Mukt Yuva for Viksit Bharat',
    issuer: 'Mera Yuva Bharat - MY Bharat',
    issuedDate: 'Aug 2026',
    credentialUrl: 'https://postimg.cc/yDXw3DSq',
    skills: ['Social Responsibility', 'Community Engagement', 'Volunteering', 'Awareness Raising', 'NSS'],
    logoType: 'generic',
  },
  {
    id: 'python-internship',
    title: 'Python Internship (6 Weeks Online Internship)',
    issuer: 'Skill Nexis',
    issuedDate: 'Jul 2026',
    credentialId: 'SNX-00089-26',
    credentialUrl: 'https://drive.google.com/file/d/10id8cRYM_mlyxjPLSEbzLLcuN_bhqidv/view',
    skills: ['Python (Programming Language)', 'Object-Oriented Programming (OOP)'],
    logoType: 'generic',
  },
  {
    id: 'claude-code-101',
    title: 'Claude Code 101',
    issuer: 'Anthropic',
    issuedDate: 'Jul 2026',
    credentialId: '3ozcos8unc6z',
    credentialUrl: 'https://verify.skilljar.com/c/3ozcos8unc6z',
    skills: ['Claude Code', 'Anthropic Claude'],
    logoType: 'generic',
  },
  {
    id: 'claude-101',
    title: 'Claude 101',
    issuer: 'Anthropic',
    issuedDate: 'Jul 2026',
    credentialId: 'utn3a8dejoj8',
    credentialUrl: 'https://verify.skilljar.com/c/utn3a8dejoj8',
    skills: ['Claude Skills', 'Artificial Intelligence (AI)'],
    logoType: 'generic',
  },
  {
    id: 'deloitte-tech',
    title: 'Deloitte Australia - Technology Job Simulation',
    issuer: 'Deloitte (via Forage)',
    issuedDate: 'Jul 2026',
    credentialId: 'tkR6rKu9bGf53fy8u',
    credentialUrl: 'https://www.theforage.com/completion-certificates/9PBTqmSxAf6zZTseP/udmxiyHeqYQLkTPvf_9PBTqmSxAf6zZTseP_6a2e7a5a4921757471accc8d_1782981863093_completion_certificate.pdf',
    skills: ['Computer Networking', 'Data Structures', 'Programming', 'Data Modeling'],
    logoType: 'deloitte',
  },
  {
    id: 'cisco-cyber',
    title: 'Introduction to Cybersecurity',
    issuer: 'Cisco Networking Academy',
    issuedDate: 'Jul 2026',
    credentialUrl: 'https://www.credly.com/badges/7988bae3-0b57-46f5-8077-196a32c533fb/linked_in_profile',
    skills: ['Cybersecurity', 'Threat Detection', 'Network Defense', 'Threat Analysis'],
    logoType: 'cisco',
  },
  {
    id: 'deloitte-cyber',
    title: 'Deloitte Australia - Cyber Job Simulation',
    issuer: 'Deloitte (via Forage)',
    issuedDate: 'Jun 2026',
    credentialId: 'ehFPNvSbB2fJE7fx8',
    credentialUrl: 'https://www.theforage.com/completion-certificates/9PBTqmSxAf6zZTseP/E9pA6qsdbeyEkp3ti_9PBTqmSxAf6zZTseP_6a2e7a5a4921757471accc8d_1782818190752_completion_certificate.pdf',
    skills: ['Data Analysis', 'Log Analysis', 'Spreadsheets', 'Networking'],
    logoType: 'deloitte',
  },
  {
    id: 'deloitte-analytics',
    title: 'Data Analytics Job Simulation',
    issuer: 'Deloitte (via Forage)',
    issuedDate: 'Jul 2026',
    credentialId: 'tCudzdjpuLzfkC8WL',
    credentialUrl: 'https://www.theforage.com/completion-certificates/9PBTqmSxAf6zZTseP/io9DzWKe3PTsiS6GG_9PBTqmSxAf6zZTseP_6a2e7a5a4921757471accc8d_1782852373192_completion_certificate.pdf',
    skills: ['Data Analysis', 'Data Visualisation', 'Data Cleaning', 'Reporting'],
    logoType: 'deloitte',
  },
  {
    id: 'datacom-software',
    title: 'Software Development Job Simulation',
    issuer: 'Datacom (via Forage)',
    issuedDate: 'Jul 2026',
    credentialId: 'hB2jkEbMzbSMZZbaH',
    credentialUrl: 'https://www.theforage.com/completion-certificates/gCW7Xki5Y3vNpBmnn/L3NcyCoAjLno9d3T9_gCW7Xki5Y3vNpBmnn_6a2e7a5a4921757471accc8d_1782851574596_completion_certificate.pdf',
    skills: ['Critical Thinking', 'Software Development', 'Root Cause Analysis', 'Development Tools', 'Software Evaluations'],
    logoType: 'generic',
  },
  {
    id: 'forage-labeling',
    title: 'Data Labeling Job Simulation',
    issuer: 'Forage',
    issuedDate: 'Jul 2026',
    credentialUrl: 'https://www.theforage.com/completion-certificates/HgpPSsyQpzob6HEh9/Fnbjyox4Y4SciuEGF_HgpPSsyQpzob6HEh9_6a2e7a5a4921757471accc8d_1782850536808_completion_certificate.pdf',
    skills: ['Analytical Skills', 'Data Privacy', 'Documentation', 'Metadata Tagging'],
    logoType: 'generic',
  },
  {
    id: 'openai-agents',
    title: 'Agents and Workflows',
    issuer: 'OpenAI',
    issuedDate: 'Jun 2026',
    credentialUrl: 'https://academy.openai.com/public/certificate/eynchdznuq',
    skills: ['Workflow Management', 'AI Agents', 'Agentic Workflows', 'Task Orchestration'],
    logoType: 'openai',
  },
  {
    id: 'openai-applied',
    title: 'Applied AI Foundations',
    issuer: 'OpenAI',
    issuedDate: 'Jun 2026',
    credentialUrl: 'https://academy.openai.com/public/certificate/ybtojhfc5i',
    skills: ['AI Prompting', 'Prompt Writing', 'Prompt Engineering', 'Generative AI'],
    logoType: 'openai',
  },
  {
    id: 'openai-foundations',
    title: 'AI Foundations',
    issuer: 'OpenAI',
    issuedDate: 'Jun 2026',
    credentialUrl: 'https://academy.openai.com/home/certificate/i8pojlo5h4',
    skills: ['Artificial Intelligence (AI)', 'Generative Models', 'Neural Networks Basics'],
    logoType: 'openai',
  },
  {
    id: 'ibm-prompting',
    title: 'Mastering the Art of Prompting',
    issuer: 'IBM',
    issuedDate: 'Mar 2026',
    credentialUrl: 'https://skills.yourlearning.ibm.com/certificate/share/c58603e180ewogICJsZWFybmVyQ05VTSIgOiAiNzMxNzU3MFJFRyIsCiAgIm9iamVjdFR5cGUiIDogIkFDVElWSVRZIiwKICAib2JqZWN0SWQiIDogIkFMTS1DT1VSU0VfNDA1ODg1OCIKfQ3e73772136-10',
    skills: ['Prompt Writing', 'AI Prompting', 'IBM Watsonx', 'LLM Tuning'],
    logoType: 'ibm',
  },
  {
    id: 'ibm-llm',
    title: 'Large Language Model Basics',
    issuer: 'IBM',
    issuedDate: 'Mar 2026',
    credentialUrl: 'https://skills.yourlearning.ibm.com/certificate/share/a338b3e4a0ewogICJsZWFybmVyQ05VTSIgOiAiNzMxNzU3MFJFRyIsCiAgIm9iamVjdFR5cGUiIDogIkFDVElWSVRZIiwKICAib2JqZWN0SWQiIDogIkFMTS1DT1VSU0VfNDA1ODg3MiIKfQac19135893-10',
    skills: ['Large Language Models (LLM)', 'Generative AI Architecture', 'Transformer Networks'],
    logoType: 'ibm',
  },
  {
    id: 'ibm-ai-students',
    title: 'Introduction to Artificial Intelligence',
    issuer: 'IBM',
    issuedDate: 'Mar 2026',
    credentialUrl: 'https://skills.yourlearning.ibm.com/certificate/share/bd71e9d771ewogICJvYmplY3RJZCIgOiAiQUxNLUNPVVJTRV80MDU4OTE4IiwKICAibGVhcm5lckNOVU0iIDogIjczMTc1NzBSRUciLAogICJvYmplY3RUeXBlIiA6ICJBQ1RJVklUWSIKfQ43e19ecdb8-10',
    skills: ['Artificial Intelligence for Students', 'Machine Learning Concepts', 'Cognitive Computing'],
    logoType: 'ibm',
  },
  {
    id: 'ibm-getting-started',
    title: 'Getting Started with Artificial Intelligence',
    issuer: 'IBM',
    issuedDate: 'Mar 2026',
    credentialUrl: 'https://www.credly.com/badges/53349b39-57c1-4917-8f46-e0d8ca2f83c0/linked_in_profile',
    skills: ['Artificial Intelligence (AI)', 'Ethics in AI', 'Machine Learning Basics'],
    logoType: 'ibm',
  },
  {
    id: 'kshitij-unstop',
    title: 'Certificate of Participation in Kascade, Kshitij 2026',
    issuer: 'IIT Kharagpur (via Unstop)',
    issuedDate: 'Jan 2026',
    credentialUrl: 'https://unstop.com/certificate-preview/ef84ce53-952d-4d99-ad0d-5a2091b94ae2?utm_campaign',
    skills: ['Mathematical Analysis', 'Discrete Mathematics', 'Analytical Skills', 'Problem Solving'],
    logoType: 'unstop',
  },
  {
    id: 'dell-codex',
    title: 'Dell Technologies Codex - Participation',
    issuer: 'Dell Technologies',
    issuedDate: '2026',
    skills: ['Competitive Coding', 'Problem Solving', 'Data Structures'],
    logoType: 'generic',
  },
  {
    id: 'soa-acm',
    title: 'SOA ACM Chapter - Participation',
    issuer: 'SOA University ACM Student Chapter',
    issuedDate: '2026',
    skills: ['Technical Collaboration', 'Computer Science Seminars', 'Community Coding'],
    logoType: 'generic',
  },
  {
    id: 'nss-appreciation',
    title: 'NSS Certificate of Appreciation',
    issuer: 'National Service Scheme (NSS)',
    issuedDate: '2025',
    skills: ['Social Welfare', 'Community Leadership', 'Event Management'],
    logoType: 'nss',
  },
  {
    id: 'nss-participation',
    title: 'NSS Certificate of Participation',
    issuer: 'National Service Scheme (NSS)',
    issuedDate: '2025',
    skills: ['Volunteer Service', 'Teamwork', 'Communication'],
    logoType: 'nss',
  },
];

export const skillCategories: SkillCategory[] = [
  {
    title: 'Programming Languages',
    color: 'from-amber-400 to-orange-500',
    skills: [
      { name: 'Java', level: 90, category: 'Core' },
      { name: 'Python', level: 80, category: 'Data/AI' },
      { name: 'SQL', level: 75, category: 'Database' },
      { name: 'C++', level: 70, category: 'Core' },
      { name: 'C', level: 65, category: 'Core' },
    ],
  },
  {
    title: 'Data Structures & OOP',
    color: 'from-blue-500 to-indigo-600',
    skills: [
      { name: 'Object-Oriented Programming (OOP)', level: 95, category: 'Pillar' },
      { name: 'Linked Lists & Arrays', level: 90, category: 'DSA' },
      { name: 'Stacks & Queues', level: 85, category: 'DSA' },
      { name: 'Searching & Sorting Algorithms', level: 85, category: 'DSA' },
      { name: 'Database Fundamentals', level: 75, category: 'Backend' },
    ],
  },
  {
    title: 'AI, Cybersecurity & Systems',
    color: 'from-emerald-400 to-teal-500',
    skills: [
      { name: 'AI Prompting / Engineering', level: 90, category: 'AI' },
      { name: 'Penetration Testing (Kali, Nmap, Burp)', level: 85, category: 'Security' },
      { name: 'Cybersecurity Principles', level: 80, category: 'Security' },
      { name: 'Threat Detection & Wireshark', level: 75, category: 'Security' },
      { name: 'Linux OS & Networking', level: 75, category: 'Systems' },
    ],
  },
  {
    title: 'Environments & AI Tools',
    color: 'from-fuchsia-500 to-purple-600',
    skills: [
      { name: 'IntelliJ IDEA & VS Code', level: 95, category: 'IDE' },
      { name: 'GitHub Copilot & Gemini', level: 95, category: 'AI Tools' },
      { name: 'Claude & ChatGPT', level: 95, category: 'AI Tools' },
      { name: 'VirtualBox & Metasploitable Labs', level: 85, category: 'Dev/Sec' },
      { name: 'Git & Version Control', level: 80, category: 'DevOps' },
    ],
  },
];

export const volunteerExp = {
  role: 'National Service Scheme (NSS) Volunteer',
  organization: 'National Service Scheme',
  description: [
    'Participated actively in community service initiatives and social awareness programs to support rural development and healthcare camps.',
    'Collaborated with fellow student volunteers in planning and executing large-scale institutional activities, blood donation drives, and environmental cleanup campaigns.',
    'Developed high-impact leadership, robust teamwork, empathetic communication, and organizational skills through active grassroot participation.',
    'Formally recognized with both a Certificate of Participation and a prestigious Certificate of Appreciation for outstanding commitment.',
  ],
};

export const otherDetails = {
  languages: [
    { name: 'English', level: 'Professional/Academic' },
    { name: 'Hindi', level: 'Spoken & Written' },
    { name: 'Odia', level: 'Native / Mother Tongue' },
    { name: 'Telugu', level: 'Conversational / Regional' },
  ],
  interests: [
    { name: 'Film & Television Analysis', icon: 'Film', desc: 'Watching and analyzing films/TV from a cinematic, storytelling, and screenwriting perspective.' },
    { name: 'Reading Novels', icon: 'BookOpen', desc: 'Exploring classic fiction, technology-related non-fiction, and sci-fi books.' },
    { name: 'Following Technology Trends', icon: 'TrendingUp', desc: 'Keeping tabs on the latest developments in LLMs, agentic AI, and cybersecurity frameworks.' },
    { name: 'Photography', icon: 'Camera', desc: 'Capturing nature, urban architectures, and local community events.' },
    { name: 'Gaming', icon: 'Gamepad2', desc: 'Playing immersive open-world games and real-time strategic challenges.' },
    { name: 'Learning Emerging Tech', icon: 'Cpu', desc: 'Tinkering with new libraries, modular languages, and software development methodologies.' },
  ],
};
